1. 二值图像 仅仅包含黑白 特殊的灰度图像

2. 灰度图像 黑到白256个灰度级 8bit 1字节 图像基本存储的数据类型 8魏


In [ ]:
## 二值图像
import cv2
import numpy as np

# positional argument follows keyword argument 
# 参数位置不对

size = 200
img = np.zeros((size,size),dtype=np.uint8)
print("img =\n",img)

cv2.imshow("one",img)
print("读取像素点 img[0,3]=",img[0,3])
# 修改像素点
for i in range(size):
    img[i,i] = 255
    
cv2.imshow("two",img) 
print("img =\n",img)
if cv2.waitKey():
    cv2.destroyAllWindows()

###  彩色图像
3. 彩色图像 
 > 光学角度 
  * 主波长
  * 纯度
  * 明度
 > 心理学视觉
  * 色调
  * 饱和度
  * 亮度
**不同方式表示颜色的模式 称为 _色彩空间_ 颜色空间 颜色模式 **
- RGB色彩模式 （R,G,B）*openCV 中通道顺序为 B G R*
  1. R 灰度图像 [0,255]
  2. G
  3. B

In [1]:
import cv2 
import numpy as np

size = 200

blue = np.zeros((size,size,3), np.uint8)
blue[:,:,0] = 255
cv2.imshow("blue",blue)

green = np.zeros((size,size,3), np.uint8)
green[:,:,1] = 255
cv2.imshow("green", green)

red = np.zeros((size,size,3), np.uint8)
red[:,:,2] = 255
cv2.imshow("red", red)

if cv2.waitKey():
    cv2.destroyAllWindows()


In [1]:
import cv2 
import numpy as np

size = 300

img = np.zeros((size,size,3), np.uint8)
img[:,0:100,0] = 255
img[:,100:200,1] = 255
img[:,200:300:,2] = 255
cv2.imshow("img", img)

if cv2.waitKey():
    cv2.destroyAllWindows()

#### 使用numpy.array访问像素

In [9]:
import numpy as np
img = np.random.randint(10,99,size=(10,20),dtype=np.uint8)
print(img)
print("读取像素点", img.item(3,2))

[[15 52 74 81 89 48 38 86 40 34 63 70 29 45 32 97 98 32 35 87]
 [30 61 42 23 41 28 94 86 25 96 80 22 88 78 10 95 81 94 71 48]
 [83 96 65 11 34 25 15 85 13 58 65 71 71 62 80 31 50 42 44 52]
 [22 59 18 14 38 13 50 84 90 42 82 86 24 51 34 33 53 56 49 52]
 [60 66 19 10 89 96 69 60 65 23 31 11 29 24 52 51 88 26 82 23]
 [19 75 55 53 74 22 41 46 78 81 43 18 14 67 42 79 10 40 10 77]
 [86 67 70 65 70 85 31 78 61 62 17 47 38 76 64 47 54 60 19 75]
 [27 61 84 38 55 21 91 83 26 44 87 19 27 41 13 17 25 98 60 83]
 [40 82 93 52 27 45 33 89 42 46 83 89 64 45 89 52 90 16 86 46]
 [35 73 72 19 30 46 73 98 44 54 74 34 74 46 77 18 93 56 64 22]]
读取像素点 18


In [ ]:
import cv2 
import numpy as np
img = np.random.randint(0,256,size=[150,150],dtype=np.uint8)
cv2.imshow("demo",img)
cv2.waitKey()
cv2.destroyAllWindows()