In [1]:
import cv2 
import numpy as np

#
img = cv2.imread("shl.jpg",0)
print("",img)
c,v = img.shape

bgr = np.ones((c,v,3), dtype = np.uint8)
bgr[:,:,0] = img
bgr[:,:,1] = img
bgr[:,:,2] = img
cv2.imshow("gray",img)
cv2.imshow("rgb",bgr)
cv2.waitKey()
cv2.destroyAllWindows()

 [[ 88  88  88 ... 121 121 121]
 [ 88  88  88 ... 121 121 121]
 [ 88  88  88 ... 122 122 121]
 ...
 [184 185 186 ... 225 225 226]
 [183 183 184 ... 226 227 227]
 [182 183 184 ... 235 235 235]]


# HSV色彩空间
1. H 色调、色相 Hue [0,360] 映射到 [0,255]
2. S 饱和度 Saturation [0,1] 映射到 [0,255]
3. V 亮度 Value   [0,1] 映射到 [0,255]

In [5]:
import cv2 
import numpy as np

#
img = cv2.imread("shl.jpg",3)
print("原图",img)
rst = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.imshow("gray",rst)
cv2.imshow("rgb",img)

rgb = cv2.cvtColor(rst,cv2.COLOR_GRAY2BGR)
cv2.imshow("复原",rgb)

print("复原",rgb)
cv2.waitKey()
cv2.destroyAllWindows()

原图 [[[170 109  16]
  [170 109  16]
  [170 109  16]
  ...
  [210 155  20]
  [210 155  20]
  [210 155  20]]

 [[170 109  16]
  [170 109  16]
  [170 109  16]
  ...
  [210 155  20]
  [210 155  20]
  [210 155  20]]

 [[170 109  16]
  [170 109  16]
  [170 109  16]
  ...
  [211 155  22]
  [211 155  22]
  [210 154  21]]

 ...

 [[193 184 181]
  [194 185 182]
  [195 186 183]
  ...
  [230 224 225]
  [230 224 225]
  [231 225 226]]

 [[192 183 180]
  [192 183 180]
  [193 184 181]
  ...
  [231 225 226]
  [232 226 227]
  [232 226 227]]

 [[191 182 179]
  [192 183 180]
  [193 184 181]
  ...
  [240 234 235]
  [240 234 235]
  [240 234 235]]]
复原 [[[ 88  88  88]
  [ 88  88  88]
  [ 88  88  88]
  ...
  [121 121 121]
  [121 121 121]
  [121 121 121]]

 [[ 88  88  88]
  [ 88  88  88]
  [ 88  88  88]
  ...
  [121 121 121]
  [121 121 121]
  [121 121 121]]

 [[ 88  88  88]
  [ 88  88  88]
  [ 88  88  88]
  ...
  [122 122 122]
  [122 122 122]
  [121 121 121]]

 ...

 [[184 184 184]
  [185 185 185]
  [186 186 186