# Numpy

* 数据选择
* Array计算

Numpy 是一个为python提供高性能向量、矩阵和高维数据结构的科学计算库。Numpy主要运算对象是多维数组

In [1]:
import numpy as np


## 数据选择
* 一维数组选择
* 多维数组选择
* 条件选择

### 一维数组选择

In [2]:
a=np.array([100,200,300,400])
a

array([100, 200, 300, 400])

#### 索引选择

In [3]:
a[3]

400

In [4]:
a[-1]

400

In [5]:
a[-2]

300

In [6]:
a[0]

100

#### 切片选择

In [7]:
a[1:3]

array([200, 300])

In [8]:
a[1:-1]

array([200, 300])

In [9]:
a[1:]

array([200, 300, 400])

In [11]:
a[1::2]

array([200, 400])

### 多维数组选择

In [12]:
a=np.array([[100,200,300,400],[4,16,32,64]])
a

array([[100, 200, 300, 400],
       [  4,  16,  32,  64]])

#### 索引选择

In [14]:
a[0][0]

100

In [15]:
a[1][2]

32

In [16]:
a[1,2]

32

In [17]:
a[1]

array([ 4, 16, 32, 64])

In [18]:
a[:,1]

array([200,  16])

In [19]:
a[:,[1,3]]

array([[200, 400],
       [ 16,  64]])

In [20]:
a[0,[-1,-2]]

array([400, 300])

#### 切片选择

In [24]:
a

array([[100, 200, 300, 400],
       [  4,  16,  32,  64]])

In [22]:
a[1:]

array([[ 4, 16, 32, 64]])

In [23]:
a[0:,2:]

array([[300, 400],
       [ 32,  64]])

In [25]:
a[:,2:]

array([[300, 400],
       [ 32,  64]])

In [26]:
a[:,-3:-1]

array([[200, 300],
       [ 16,  32]])

In [27]:
a[:,-4:-1:2]

array([[100, 300],
       [  4,  32]])

In [28]:
a[...,-3:-1]

array([[200, 300],
       [ 16,  32]])

In [30]:
a

array([[100, 200, 300, 400],
       [  4,  16,  32,  64]])

#### 切片和索引选择

In [29]:
a[1,:2]

array([ 4, 16])

In [32]:
a[0,[1,2,-1]]

array([200, 300, 400])

#### 条件选择

In [33]:
a

array([[100, 200, 300, 400],
       [  4,  16,  32,  64]])

In [35]:
a[a>50]

array([100, 200, 300, 400,  64])

In [36]:
(a>50) & (a<=300)

array([[ True,  True,  True, False],
       [False, False, False,  True]])

In [37]:
a[(a>50) & (a<=300)]

array([100, 200, 300,  64])

In [38]:
(a<=50) | (a>300)

array([[False, False, False,  True],
       [ True,  True,  True, False]])

In [39]:
a[(a<=50) | (a>300)]

array([400,   4,  16,  32])

## Array 计算

In [40]:
a=np.array([1,4,9,16])
b=np.array([25,36,49,64])
print(a)
print(b)

[ 1  4  9 16]
[25 36 49 64]


In [41]:
a*2

array([ 2,  8, 18, 32])

In [42]:
a*4

array([ 4, 16, 36, 64])

In [43]:
a+1

array([ 2,  5, 10, 17])

In [44]:
a-1

array([ 0,  3,  8, 15])

In [45]:
a/3

array([0.33333333, 1.33333333, 3.        , 5.33333333])

In [46]:
a//3

array([0, 1, 3, 5], dtype=int32)

In [47]:
a%3

array([1, 1, 0, 1], dtype=int32)

In [49]:
a

array([ 1,  4,  9, 16])

In [50]:
b

array([25, 36, 49, 64])

In [48]:
a+b

array([26, 40, 58, 80])

In [51]:
b-a

array([24, 32, 40, 48])

In [52]:
a*b

array([  25,  144,  441, 1024])

In [53]:
a/b

array([0.04      , 0.11111111, 0.18367347, 0.25      ])

In [54]:
a//b

array([0, 0, 0, 0], dtype=int32)

In [57]:
b%a

array([0, 0, 4, 0], dtype=int32)

## 课后练习

In [5]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
选择第一行第二列的数据

In [ ]:
选择第三列的数据

In [ ]:
选择所有在第二第三行，第四第五列的数据

In [ ]:
第一行每个数据加一，第二行每个数据加二，其他数据不变

In [ ]:
第一列每个数据*2，第二列每个数据*3，其他数据不变