# Numpy

* 计算
* 排序
* 提取
* 保存和读入

In [1]:
import numpy as np

## 计算
* 统计计算
* 估算

### 统计计算

In [3]:
a=np.array([(1,4,9,16),(100,200,300,400)])
a

array([[  1,   4,   9,  16],
       [100, 200, 300, 400]])

In [4]:
np.sum(a)

1030

In [5]:
np.sum(a,axis=1)

array([  30, 1000])

In [6]:
np.sum(a,axis=0)

array([101, 204, 309, 416])

In [7]:
np.cumsum(a)

array([   1,    5,   14,   30,  130,  330,  630, 1030], dtype=int32)

In [8]:
np.cumsum(a,axis=1)

array([[   1,    5,   14,   30],
       [ 100,  300,  600, 1000]], dtype=int32)

In [9]:
np.cumsum(a,axis=0)

array([[  1,   4,   9,  16],
       [101, 204, 309, 416]], dtype=int32)

In [10]:
a

array([[  1,   4,   9,  16],
       [100, 200, 300, 400]])

In [11]:
np.mean(a)

128.75

In [12]:
np.mean(a,axis=1)

array([  7.5, 250. ])

In [13]:
np.mean(a,axis=0)

array([ 50.5, 102. , 154.5, 208. ])

In [14]:
np.average(a)

128.75

In [15]:
np.average(a,axis=1)

array([  7.5, 250. ])

In [16]:
np.average(a,axis=1,weights=[1,2,3,4])

array([ 10., 300.])

In [17]:
np.median(a)

58.0

In [19]:
np.median(a,axis=0)

array([ 50.5, 102. , 154.5, 208. ])

In [20]:
np.percentile(a,q=[50,100])

array([ 58., 400.])

In [21]:
np.percentile(a,q=[25,50,100])

array([  7.75,  58.  , 400.  ])

In [23]:
np.percentile(a,q=[25,50,100],axis=1).T

array([[  3.25,   6.5 ,  16.  ],
       [175.  , 250.  , 400.  ]])

In [24]:
np.var(a)

20967.6875

In [25]:
np.var(a,axis=1)

array([   32.25, 12500.  ])

In [26]:
np.std(a)

144.80223582527998

In [27]:
np.std(a,axis=1)

array([  5.67890835, 111.80339887])

In [28]:
np.min(a)

1

In [29]:
np.min(a,axis=1)

array([  1, 100])

In [30]:
np.max(a)

400

In [31]:
np.max(a,axis=1)

array([ 16, 400])

In [32]:
a

array([[  1,   4,   9,  16],
       [100, 200, 300, 400]])

In [33]:
np.argmax(a)

7

In [34]:
np.argmax(a,axis=1)

array([3, 3], dtype=int64)

In [35]:
np.argmin(a)

0

In [37]:
np.argmin(a,axis=0)

array([0, 0, 0, 0], dtype=int64)

### 估算

In [38]:
np.round([4.5,6.6,1.4,8.9])

array([4., 7., 1., 9.])

In [44]:
np.round(15.5)

16.0

In [45]:
np.floor([4.5,6.6,1.4,8.9])

array([4., 6., 1., 8.])

In [46]:
np.ceil([4.5,6.6,1.4,8.9])

array([5., 7., 2., 9.])

## 排序

In [48]:
a=np.array([[200,400,100,300],[25,16,9,81]])
a

array([[200, 400, 100, 300],
       [ 25,  16,   9,  81]])

In [49]:
np.sort(a)

array([[100, 200, 300, 400],
       [  9,  16,  25,  81]])

In [50]:
np.sort(a,axis=0)

array([[ 25,  16,   9,  81],
       [200, 400, 100, 300]])

In [63]:
np.sort(a,axis=0)[::-1]

array([[200, 400, 100, 300],
       [ 25,  16,   9,  81]])

In [65]:
-np.sort(-a)

array([[400, 300, 200, 100],
       [ 81,  25,  16,   9]])

In [66]:
np.argsort(a)

array([[2, 0, 3, 1],
       [2, 1, 0, 3]], dtype=int64)

In [67]:
a

array([[200, 400, 100, 300],
       [ 25,  16,   9,  81]])

In [68]:
np.sort(a)

array([[100, 200, 300, 400],
       [  9,  16,  25,  81]])

## 提取

In [69]:
a

array([[200, 400, 100, 300],
       [ 25,  16,   9,  81]])

In [71]:
a[a>50]

array([200, 400, 100, 300,  81])

In [73]:
np.where(a>50)

(array([0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 3], dtype=int64))

In [75]:
np.where(a>50,'>50','<=50')

array([['>50', '>50', '>50', '>50'],
       ['<=50', '<=50', '<=50', '>50']], dtype='<U4')

In [77]:
np.where(a>50,a,'<=50')

array([['200', '400', '100', '300'],
       ['<=50', '<=50', '<=50', '81']], dtype='<U11')

In [79]:
np.extract(a>50,a)

array([200, 400, 100, 300,  81])

## 保存和读入
* npy文件
* npz文件
* txt文件

### npy文件

In [81]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
b=np.arange(8).reshape(2,-1)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
np.save('example.npy',a)


In [84]:
np.load('example.npy')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### npz文件

In [85]:
np.savez('example.npz',a,b)

In [86]:
file=np.load('example.npz')

In [88]:
file.files

['arr_0', 'arr_1']

In [89]:
file['arr_0']

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
file['arr_1']

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### txt文件

In [91]:
np.savetxt('example.txt',a)

In [93]:
np.loadtxt('example.txt',dtype='int32')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
np.savetxt('example.txt',a,fmt='%1d',delimiter=',')

In [97]:
np.savetxt('example.txt',a,fmt='%.2f',delimiter=',')

In [100]:
np.loadtxt('example.txt',delimiter=',',dtype='str')

array([['0.00', '1.00', '2.00', '3.00', '4.00'],
       ['5.00', '6.00', '7.00', '8.00', '9.00']], dtype='<U4')

## 课后练习

In [15]:
a=np.arange(12).reshape(3,4)  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
计算a每行的平均值

寻找每列最大值并返回index

In [ ]:
对每行排序，从大到小，命名为b

In [ ]:
保存b为exercise.npy的文件