# 《数据分析工具箱：Python篇》课后习题

In [58]:
import pandas as pd
import numpy as np

## 第2节课 数据类型与Array产生

### 1.随机产生一个3维（4,3,5）的数组。数值为0到1之间。 seed设为0

### 2.产生一个2维（3，5）的等差数组，数字为0到14

In [61]:
np.random.seed(0)
np.random.random((4,3,5))

array([[[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
        [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
        [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]],

       [[0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
        [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
        [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194]],

       [[0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
        [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
        [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672]],

       [[0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
        [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
        [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559]]])

In [64]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 第二节课 数据选择 Numpy计算

In [65]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1.选择第一行第二列的数据

### 2.选择第三列的数据

### 3.选择所有在第二第三行，第四第五列的数据

### 4.第一行每个数据加一，第二行每个数据加二，其他数据不变

### 5.第一列每个数据 $\times$ 2，第二列每个数据 $\times$ 3，其他数据不变

In [66]:
a[0,1]

1

In [67]:
a[:,2]

array([ 2,  7, 12])

In [70]:
a[1:,3:]

array([[ 8,  9],
       [13, 14]])

In [74]:
a+np.array([[1],[2],[0]])

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14]])

In [75]:
a*np.array([2,3,1,1,1])

array([[ 0,  3,  2,  3,  4],
       [10, 18,  7,  8,  9],
       [20, 33, 12, 13, 14]])

## 第三节课 

In [30]:
a=np.arange(12).reshape(3,4)  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1.深层拷贝a，命名为b

### 2.把b的第三行，第四列的数据变成8

### 3.把a按行展开

### 4.把a按列展开

In [34]:
b=a.copy()
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b[2,3]=8
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10,  8]])

In [37]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 第三节课-2

In [42]:
a=np.arange(12).reshape(3,4)  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1.计算a每行的平均值

### 2.寻找每列最大值并返回index

### 3.对每行排序，从大到小，命名为b

### 4.保存b为exercise.npy的文件

In [45]:
a.mean(axis=1)

array([1.5, 5.5, 9.5])

In [49]:
a.argmax(axis=0)

array([2, 2, 2, 2], dtype=int64)

In [57]:
b=-np.sort(-a)
b

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [ ]:
np.save('exercise.npy',b)


## 第四节课 Pandas Series创建，性质，Index排序

### 1.用两种方法创建一个学生成绩的series，student a 86分，student b 90分，student c 75分，student d 100分

### 2.产生包括所有学生的list

### 3.产生所有分数的list

In [82]:
score=pd.Series([86,90,75,100],index=['student a','student b','student c','student d'])
score

student a     86
student b     90
student c     75
student d    100
dtype: int64

In [81]:
pd.Series({'student a':86,'student b':90,'student c':75,'student d':100})

student a     86
student b     90
student c     75
student d    100
dtype: int64

In [84]:
score.index.tolist()

['student a', 'student b', 'student c', 'student d']

In [86]:
score.values.tolist()

[86, 90, 75, 100]

### 4.选出student c的成绩

### 5.选出分数高于85分的学生

In [89]:
score['student c']

75

In [93]:
score[score>85].index.tolist()

['student a', 'student b', 'student d']

### 第四节课 Pandas 计算 缺失数据处理

### 1.创建一个学生数学成绩的series，student a 86分，student b 90分，student c 75分，student d 100分

### 2.创建一个学生语文成绩的series，student a 100分，student b 60分，student c 85分，student d 98分

### 3.计算每个学生的平均分

### 4.计算每个学生数学和语文的分数差绝对值

In [94]:
math=pd.Series([86,90,75,100],index=['student a','student b','student c','student d'])
math

student a     86
student b     90
student c     75
student d    100
dtype: int64

In [96]:
chinese=pd.Series([100,60,85,98],index=['student a','student b','student c','student d'])
chinese

student a    100
student b     60
student c     85
student d     98
dtype: int64

In [102]:
(math+chinese)/2

student a   93.0
student b   75.0
student c   80.0
student d   99.0
dtype: float64

In [103]:
abs(math-chinese)

student a    14
student b    30
student c    10
student d     2
dtype: int64

## 第五节课 Dataframe创建，选择

In [105]:
df = pd.DataFrame({
    'ticker': ['AAPL', 'AAPL', 'MSFT', 'IBM', 'YHOO'],
    'date': ['2015-12-30', '2015-12-31', '2015-12-30', '2015-12-30', '2015-12-30'],
    'open': [426.23, 427.81, 42.3, 101.65, 35.53]
})

### 1.用两种方法选择open，结果是一个series

### 2.选择open，结果是一个dataframe

In [106]:
df['open']

0   426.2
1   427.8
2    42.3
3   101.7
4    35.5
Name: open, dtype: float64

In [112]:
df.iloc[:,2]

0   426.2
1   427.8
2    42.3
3   101.7
4    35.5
Name: open, dtype: float64

In [114]:
df[['open']]

open
0 426.2
1 427.8
2  42.3
3 101.7
4  35.5

## 第五节课 多维选择条件选择安全选择，不安全选择，index

In [115]:
df = pd.DataFrame({
    'ticker': ['AAPL', 'AAPL', 'MSFT', 'IBM', 'YHOO'],
    'date': ['2015-12-30', '2015-12-31', '2015-12-30', '2015-12-30', '2015-12-30'],
    'open': [426.23, 427.81, 42.3, 101.65, 35.53]
})

### 1.对所有ticker是AAPL的行，选择date和open

### 2.通过df新建一个df1，df1以ticker作为index

### 3.通过df1新建一个df2，以date作为index

### 4.通过index 排序df2，递增排序


In [116]:
df[df['ticker']=='AAPL'][['date','open']]

date  open
0  2015-12-30 426.2
1  2015-12-31 427.8

In [119]:
df1=df.set_index('ticker')
df1

date  open
ticker                  
AAPL    2015-12-30 426.2
AAPL    2015-12-31 427.8
MSFT    2015-12-30  42.3
IBM     2015-12-30 101.7
YHOO    2015-12-30  35.5

In [121]:
df2=df1.set_index('date')
df2

open
date            
2015-12-30 426.2
2015-12-31 427.8
2015-12-30  42.3
2015-12-30 101.7
2015-12-30  35.5

In [122]:
df2.sort_index()

open
date            
2015-12-30 426.2
2015-12-30  42.3
2015-12-30 101.7
2015-12-30  35.5
2015-12-31 427.8

## 第五节课 dataframe修改，错误修改，保存

In [123]:
df = pd.DataFrame({
    'ticker': ['AAPL', 'AAPL', 'MSFT', 'IBM', 'YHOO'],
    'date': ['2015-12-30', '2015-12-31', '2015-12-30', '2015-12-30', '2015-12-30'],
    'open': [426.23, 427.81, 42.3, 101.65, 35.53]
})

### 1.复制一个df，命名为df3。 新增一个close column，对open值大于100的行数，open等于close，其余行close是nan

### 2.对df3基于close排序，递减排序

In [124]:
df3=df.copy()

In [125]:
df3.loc[df3['open']>100,'close']=df3['open']
df3

ticker        date  open  close
0   AAPL  2015-12-30 426.2  426.2
1   AAPL  2015-12-31 427.8  427.8
2   MSFT  2015-12-30  42.3    nan
3    IBM  2015-12-30 101.7  101.7
4   YHOO  2015-12-30  35.5    nan

In [127]:
df3.sort_values(['close'],ascending=False)

ticker        date  open  close
1   AAPL  2015-12-31 427.8  427.8
0   AAPL  2015-12-30 426.2  426.2
3    IBM  2015-12-30 101.7  101.7
2   MSFT  2015-12-30  42.3    nan
4   YHOO  2015-12-30  35.5    nan

## 第六节课 Dataframe性质

### 1.创建一个学生成绩的dataframe，数学成绩 student a 86分，student b 90分，student c 75分，student d 100分，语文成绩 student a 100分，student b 60分，student c 85分，student d 98分

### 2.列出score的column,index和value

### 3.计算数学成绩和语文成绩的分布

In [129]:
score=pd.DataFrame({'math':[86,90,75,100],
             'chinese':[100,60,85,98]},index=['student a','student b','student c','student d'])

score

math  chinese
student a    86      100
student b    90       60
student c    75       85
student d   100       98

In [130]:
score.columns

Index(['math', 'chinese'], dtype='object')

In [131]:
score.index

Index(['student a', 'student b', 'student c', 'student d'], dtype='object')

In [135]:
score.values

array([[ 86, 100],
       [ 90,  60],
       [ 75,  85],
       [100,  98]], dtype=int64)

In [136]:
score.describe()

math  chinese
count   4.0      4.0
mean   87.8     85.8
std    10.3     18.4
min    75.0     60.0
25%    83.2     78.8
50%    88.0     91.5
75%    92.5     98.5
max   100.0    100.0

## 第六节课 copy，缺失数据处理：fillna，dropna

In [151]:
df = pd.DataFrame({
   'ticker': ['AAPL', 'AAPL', 'AAPL','MSFT', 'IBM', 'YHOO'],
    'date': ['2015-12-30', '2015-12-31', '2015-12-30', '2015-12-29','2015-12-31', '2015-12-31'],
    'open': [426.23, 500.51, 42.3, 101.65, 35.53,np.nan]})

### 1.复制一个df，命名为df2

### 2.向前填充缺失值

### 3.删除包含缺失值的row

### 4.删除包含缺失值的column

### 5.对每个ticker，只保留最近一条记录

### 6.删除date

### 7.删除第一行记录

In [152]:
df2=df.copy()

In [153]:
df2.ffill()

ticker        date  open
0   AAPL  2015-12-30 426.2
1   AAPL  2015-12-31 500.5
2   AAPL  2015-12-30  42.3
3   MSFT  2015-12-29 101.7
4    IBM  2015-12-31  35.5
5   YHOO  2015-12-31  35.5

In [154]:
df2.dropna()

ticker        date  open
0   AAPL  2015-12-30 426.2
1   AAPL  2015-12-31 500.5
2   AAPL  2015-12-30  42.3
3   MSFT  2015-12-29 101.7
4    IBM  2015-12-31  35.5

In [155]:
df2.dropna(axis=1)

ticker        date
0   AAPL  2015-12-30
1   AAPL  2015-12-31
2   AAPL  2015-12-30
3   MSFT  2015-12-29
4    IBM  2015-12-31
5   YHOO  2015-12-31

In [156]:
df2.sort_values(['ticker','date']).drop_duplicates(subset=['ticker'],keep='last')

ticker        date  open
1   AAPL  2015-12-31 500.5
4    IBM  2015-12-31  35.5
3   MSFT  2015-12-29 101.7
5   YHOO  2015-12-31   nan

In [158]:
df2.drop(['date'],axis=1)

ticker  open
0   AAPL 426.2
1   AAPL 500.5
2   AAPL  42.3
3   MSFT 101.7
4    IBM  35.5
5   YHOO   nan

In [160]:
df2.drop(0,axis=0)

ticker        date  open
1   AAPL  2015-12-31 500.5
2   AAPL  2015-12-30  42.3
3   MSFT  2015-12-29 101.7
4    IBM  2015-12-31  35.5
5   YHOO  2015-12-31   nan

## 第七节课

In [32]:
import numpy as np
import pandas as pd

pd.set_option('display.float_format', '{:,.1f}'.format)

In [3]:
dat = pd.read_csv('./data/weather-6m.csv')

### 1.计算每个月 `air_temp` 的平均值

### 2.用 describe 描述 air_temp 和 dew_point

### 3.只对1月和2月, 计算每小时air_temp 的平均值和std

### 4.计算每月air_temp 的分位数[0.2,0.4,0.6,0.8]

In [6]:
dat.groupby(['month'])[['air_temp']].mean()

air_temp
month          
1        -100.1
2         -29.5
3          21.0
4          70.3
5         139.8
6         180.6

In [7]:
dat['air_temp'].describe()

count   4,161.0
mean       47.4
std       114.0
min      -294.0
25%       -33.0
50%        44.0
75%       133.0
max       333.0
Name: air_temp, dtype: float64

In [8]:
dat['dew_point'].describe()

count   4,161.0
mean       -9.8
std       105.9
min      -328.0
25%       -83.0
50%       -11.0
75%        72.0
max       233.0
Name: dew_point, dtype: float64

In [10]:
dat[dat['month']<=2].groupby(['hour'])['air_temp'].agg(['mean','std'])

mean  std
hour           
0    -57.0 70.7
1    -63.7 71.0
2    -68.7 71.3
3    -71.6 72.8
4    -75.4 73.4
5    -78.2 70.5
6      nan  nan
7    -80.9 75.4
8    -81.8 75.0
9    -84.2 75.5
10   -86.9 76.2
11   -87.7 76.9
12   -87.4 76.2
13   -87.8 76.9
14   -82.9 76.1
15   -72.4 74.1
16   -63.9 72.0
17   -53.7 68.7
18   -45.2 66.4
19   -40.0 66.6
20   -37.1 66.5
21   -37.3 66.7
22   -39.7 66.7
23   -47.3 67.7

In [11]:
dat.groupby(['month'])['air_temp'].apply(lambda x:x.quantile([0.2,0.4,0.6,0.8]))

month     
1      0.2   -144.0
       0.4   -117.0
       0.6    -83.0
       0.8    -39.2
2      0.2    -89.0
       0.4    -50.0
       0.6    -10.2
       0.8     22.0
3      0.2    -33.0
       0.4     11.0
       0.6     33.0
       0.8     72.0
4      0.2     22.0
       0.4     44.0
       0.6     67.0
       0.8    111.0
5      0.2    100.0
       0.4    128.0
       0.6    150.0
       0.8    178.0
6      0.2    128.0
       0.4    161.0
       0.6    194.0
       0.8    239.0
Name: air_temp, dtype: float64

In [12]:
dat.groupby(['month']).apply(lambda x:x['air_temp'].quantile([0.2,0.4,0.6,0.8]))

air_temp    0.2    0.4   0.6   0.8
month                             
1        -144.0 -117.0 -83.0 -39.2
2         -89.0  -50.0 -10.2  22.0
3         -33.0   11.0  33.0  72.0
4          22.0   44.0  67.0 111.0
5         100.0  128.0 150.0 178.0
6         128.0  161.0 194.0 239.0

## 第七节课

In [13]:
dat = pd.read_csv('./data/weather-6m.csv')

### 1.计算每个air_temp 基于每月平均值的zscore

### 2.随机选取50个数据，运用随机产生的数据，对每个月计算，数据量在每天的分布， 比如 10%的数据在第一天采集到

### 3.在dat数据基础上，重新生成一个代表每天air_temp平均值的column,命名为daily_air_temp

### 4.在dat中去掉每日最大air_temp 小于10的日子

In [16]:
dat.groupby(['month'])[['air_temp']].apply(lambda x:(x-x.mean())/x.std())

air_temp
0         -0.5
1         -0.5
2         -0.4
3         -0.3
4         -0.2
...        ...
4335      -0.0
4336       0.1
4337       0.0
4338       0.1
4339       0.0

[4340 rows x 1 columns]

In [23]:
dat.sample(50,random_state=1).groupby(['month']).apply(lambda x:x.groupby('day').size()*100/len(x))

month  day
1      1     33.3
       23    33.3
       24    33.3
2      1     16.7
       7     16.7
       12    16.7
       13    16.7
       18    16.7
       21    16.7
3      1     12.5
       22    12.5
       23    25.0
       26    25.0
       30    12.5
       31    12.5
4      4     10.0
       7     20.0
       10    10.0
       11    10.0
       13    10.0
       19    10.0
       26    10.0
       28    10.0
       29    10.0
5      7     28.6
       14    14.3
       19    14.3
       23    14.3
       24    14.3
       29    14.3
6      1      6.2
       3      6.2
       4      6.2
       6      6.2
       10     6.2
       14    18.8
       15     6.2
       18     6.2
       24     6.2
       25     6.2
       26     6.2
       27     6.2
       28    12.5
dtype: float64

In [25]:
dat['daily_air_temp']=dat.groupby(['month','day'])['air_temp'].transform('mean')

In [26]:
dat.groupby(['month','day']).filter(lambda x:x['air_temp'].max()>=10)

year  month  day  hour  air_temp  dew_point  wind_speed  daily_air_temp
71    2009      1    4     0      11.0      -44.0        93.0             1.7
72    2009      1    4     1      11.0      -44.0        88.0             1.7
73    2009      1    4     2      11.0      -39.0        82.0             1.7
74    2009      1    4     3      17.0      -39.0        93.0             1.7
75    2009      1    4     4      11.0      -33.0        77.0             1.7
...    ...    ...  ...   ...       ...        ...         ...             ...
4335  2009      6   30    19     178.0      111.0        41.0           175.1
4336  2009      6   30    20     189.0      117.0        46.0           175.1
4337  2009      6   30    21     183.0      111.0        36.0           175.1
4338  2009      6   30    22     189.0      111.0        46.0           175.1
4339  2009      6   30    23     183.0      117.0        46.0           175.1

[3237 rows x 8 columns]

### 第八节课 Merge，join，combine。创建sampledata，inner/left/right/outer/full Join。多列join

In [162]:
import io
prc = pd.read_csv(
    io.StringIO('ticker,open,date,close\nAAPL,426.23,2018-01-04,435.23\nMSFT,42.3,2018-01-04,51.3\nAAPL,436.23,2018-01-05,\nMSFT,52.3,2018-01-05,\n'),
    parse_dates=['date']
)
prc2 = prc.assign(
    date=pd.to_datetime('2018-01-06'),
    close=prc.open + np.random.randn(len(prc.open))
).drop('open', axis=1)

In [163]:
volume = pd.DataFrame({
    'ticker': ['AAPL', 'MSFT', 'IBM', 'YHOO', 'GOOG'],
    'volume': [1954.73,  335.83,  362.79,  858.18,  629.79]
}).assign(date=pd.to_datetime('2018-01-05'))

**通过`ticker, date` merge `prc` 和 `volume`:**

### 1.保留在 prc 和 volume 中都存在的 `ticker` 和 `date`

### 2.保留 `prc` 中的所有行

### 3.保留所有出现在 `prc` 和 `volume` 中的行


In [165]:
cols = ['ticker', 'date']
pd.merge(prc, volume, on=cols)

ticker  open       date  close  volume
0   AAPL 436.2 2018-01-05    nan 1,954.7
1   MSFT  52.3 2018-01-05    nan   335.8

In [166]:
pd.merge(prc, volume, on=cols, how='left')

ticker  open       date  close  volume
0   AAPL 426.2 2018-01-04  435.2     nan
1   MSFT  42.3 2018-01-04   51.3     nan
2   AAPL 436.2 2018-01-05    nan 1,954.7
3   MSFT  52.3 2018-01-05    nan   335.8

In [167]:
pd.merge(prc, volume, on=cols, how='outer')

ticker  open       date  close  volume
0   AAPL 426.2 2018-01-04  435.2     nan
1   MSFT  42.3 2018-01-04   51.3     nan
2   AAPL 436.2 2018-01-05    nan 1,954.7
3   MSFT  52.3 2018-01-05    nan   335.8
4    IBM   nan 2018-01-05    nan   362.8
5   YHOO   nan 2018-01-05    nan   858.2
6   GOOG   nan 2018-01-05    nan   629.8

## 第八节课 Concatenation/Binding

In [171]:
import io

import numpy as np
import pandas as pd

pd.set_option('precision', 2)
prc = pd.read_csv(
    io.StringIO('ticker,open,date,close\nAAPL,426.23,2018-01-04,435.23\nMSFT,42.3,2018-01-04,51.3\nAAPL,436.23,2018-01-05,\nMSFT,52.3,2018-01-05,\n'),
    parse_dates=['date']
)
prc2 = prc.assign(
    date=pd.to_datetime('2018-01-06'),
    close=prc.open + np.random.randn(len(prc.open))
).drop('open', axis=1)

In [172]:
volume = pd.DataFrame({
    'ticker': ['AAPL', 'MSFT', 'IBM', 'YHOO', 'GOOG'],
    'volume': [1954.73,  335.83,  362.79,  858.18,  629.79]
}).assign(date=pd.to_datetime('2018-01-05'))

### 1.通过append, 合并prc2 和prc, 保证index不重复

### 2.应用 pd.concat, 合并prc和prc2：
* 确保index不重复
* 只保留在prc和prc2都出现的column，从新产生一个index
* 结果包括MultiIndex，用prc或prc2表示每个dataframe

In [175]:
prc.append(prc2,ignore_index=True)

ticker  open       date  close
0   AAPL 426.2 2018-01-04  435.2
1   MSFT  42.3 2018-01-04   51.3
2   AAPL 436.2 2018-01-05    nan
3   MSFT  52.3 2018-01-05    nan
4   AAPL   nan 2018-01-06  425.6
5   MSFT   nan 2018-01-06   41.9
6   AAPL   nan 2018-01-06  435.6
7   MSFT   nan 2018-01-06   51.9

In [177]:
pd.concat([prc,prc2],ignore_index=True)

ticker  open       date  close
0   AAPL 426.2 2018-01-04  435.2
1   MSFT  42.3 2018-01-04   51.3
2   AAPL 436.2 2018-01-05    nan
3   MSFT  52.3 2018-01-05    nan
4   AAPL   nan 2018-01-06  425.6
5   MSFT   nan 2018-01-06   41.9
6   AAPL   nan 2018-01-06  435.6
7   MSFT   nan 2018-01-06   51.9

In [180]:
pd.concat([prc,prc2],ignore_index=True,join='inner')

ticker       date  close
0   AAPL 2018-01-04  435.2
1   MSFT 2018-01-04   51.3
2   AAPL 2018-01-05    nan
3   MSFT 2018-01-05    nan
4   AAPL 2018-01-06  425.6
5   MSFT 2018-01-06   41.9
6   AAPL 2018-01-06  435.6
7   MSFT 2018-01-06   51.9

In [189]:
pd.concat([prc,prc2],keys=['prc','prc2'])

ticker  open       date  close
prc  0   AAPL 426.2 2018-01-04  435.2
     1   MSFT  42.3 2018-01-04   51.3
     2   AAPL 436.2 2018-01-05    nan
     3   MSFT  52.3 2018-01-05    nan
prc2 0   AAPL   nan 2018-01-06  425.6
     1   MSFT   nan 2018-01-06   41.9
     2   AAPL   nan 2018-01-06  435.6
     3   MSFT   nan 2018-01-06   51.9

## 第九节课

In [197]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})


### 1.通过pivot转变数据格式，以bar作为index，foo作为column，zoo 为value

### 2.通过melt把数据格式恢复

In [201]:
pt=df.pivot(index='bar',columns='foo',values=['zoo'])
pt

zoo    
foo one two
bar        
A     x   q
B     y   w
C     z   t

In [205]:
pt.columns

MultiIndex([('zoo', 'one'),
            ('zoo', 'two')],
           names=[None, 'foo'])

In [210]:
pt=pt.droplevel(0,axis=1)
pt

foo one two
bar        
A     x   q
B     y   w
C     z   t

In [221]:
pt.reset_index().melt(id_vars='bar',value_name='zoo')

bar  foo zoo
0   A  one   x
1   B  one   y
2   C  one   z
3   A  two   q
4   B  two   w
5   C  two   t

## 第九节课 高级 Merging & Reshaping

In [ ]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
                           'two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

### 1.对每一个foo,和 bar的组合，算出 baz 的平均值

### 2.改变数据结构，以foo为index，bar为column，baz作为value

3.改变数据结构，以bar为index，foo为column，baz作为value

In [223]:
df.groupby(['foo','bar'])['baz'].mean()

foo  bar
one  A      1
     B      2
     C      3
two  A      4
     B      5
     C      6
Name: baz, dtype: int64

In [224]:
df.pivot_table(index='foo',columns='bar',values=['baz'],aggfunc='mean')

baz      
bar   A  B  C
foo          
one   1  2  3
two   4  5  6

In [226]:
df.pivot_table(index='bar',columns='foo',values=['baz'],aggfunc='mean')

baz    
foo one two
bar        
A     1   4
B     2   5
C     3   6

第十节课-1

In [236]:
sp5_df = pd.read_csv(
    'sp500.csv', usecols=['date', 'adj_close'])

1.把date列的变为时间类型

2.通过date列，产生年，月，日 列

3.对 date 加 5 分钟

In [237]:
df['date']=pd.to_datetime(df['date'])

In [238]:
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day

In [239]:
import datetime
df['date']+datetime.timedelta(minutes=5)

0   2015-12-29 00:05:00
1   2015-12-30 00:05:00
2   2015-12-31 00:05:00
3   2016-01-04 00:05:00
4   2015-12-29 00:05:00
5   2015-12-30 00:05:00
6   2015-12-31 00:05:00
7   2016-01-04 00:05:00
Name: date, dtype: datetime64[ns]

第十节课-2

In [240]:
sp5_df = pd.read_csv(
    'sp500.csv', usecols=['date', 'adj_close'], 
    parse_dates=['date'])

1.产生一个时间数据 January 1st, 1993 16:00 

2.产生一个时间index:

    从2010-1-1开始，连续5天.
    
    从2010-1-1到2010-1-15，所有的工作日

3.通过sp5_df的adj_close产生一个series,date作为index,并且对index排序. 新series的名字为sp5

4.用两种不同的方法选择1995,1,3

5.选择sp5中所有1995年3月的数据



In [241]:
pd.Timestamp('1993-01-01 16:00')


Timestamp('1993-01-01 16:00:00')

In [242]:
pd.date_range(start='2010-01-01', periods=5, freq='D')

pd.date_range(start='2010-01-01', end='2010-01-15', freq='B')


DatetimeIndex(['2010-01-01', '2010-01-04', '2010-01-05', '2010-01-06',
               '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
               '2010-01-13', '2010-01-14', '2010-01-15'],
              dtype='datetime64[ns]', freq='B')

In [251]:
sp5 = pd.Series(sp5_df.adj_close.values, index=sp5_df.date, 
    name='adj_close').sort_index()
sp5

date
1950-01-03      16.7
1950-01-04      16.9
1950-01-05      16.9
1950-01-06      17.0
1950-01-09      17.1
               ...  
2016-04-06   2,066.7
2016-04-07   2,041.9
2016-04-08   2,047.6
2016-04-11   2,042.0
2016-04-12   2,061.7
Name: adj_close, Length: 16676, dtype: float64

In [244]:
d1a = sp5['19950103']
d1b = sp5['1995-01-03']
d1c = sp5[datetime.datetime(1995, 1, 3)]

In [247]:
sp5['1995-03']


date
1995-03-01   485.6
1995-03-02   485.1
1995-03-03   485.4
1995-03-06   485.6
1995-03-07   482.1
1995-03-08   483.1
1995-03-09   483.2
1995-03-10   489.6
1995-03-13   490.0
1995-03-14   492.9
1995-03-15   491.9
1995-03-16   495.4
1995-03-17   495.5
1995-03-20   496.1
1995-03-21   495.1
1995-03-22   495.7
1995-03-23   496.0
1995-03-24   501.0
1995-03-27   503.2
1995-03-28   503.9
1995-03-29   503.1
1995-03-30   502.2
1995-03-31   500.7
Name: adj_close, dtype: float64

第十节课-3

In [248]:
sp5_df = pd.read_csv(
    'sp500.csv', usecols=['date', 'adj_close'], 
    parse_dates=['date'])

1.计算每一天adj_close相较于前一天变化的百分比

2.用resample计算sp5_df的 adj_close 的月平均值


In [249]:
sp5_df['adj_close'] / sp5_df['adj_close'].shift(1) - 1


0        nan
1       -0.0
2        0.0
3       -0.0
4        0.0
        ... 
16671    0.0
16672   -0.0
16673   -0.0
16674   -0.0
16675   -0.0
Name: adj_close, Length: 16676, dtype: float64

In [250]:
sp5_df.set_index('date').resample('M').mean()

adj_close
date                 
1950-01-31       16.9
1950-02-28       17.2
1950-03-31       17.3
1950-04-30       17.8
1950-05-31       18.4
...               ...
2015-12-31    2,054.1
2016-01-31    1,918.6
2016-02-29    1,904.4
2016-03-31    2,022.0
2016-04-30    2,055.5

[796 rows x 1 columns]