# numpy


In [8]:
import numpy as np
pow(1,-0.5)

1.0

In [10]:
b = np.random.normal(0.0, pow(3, -0.5), (3,3))
b

array([[-0.72433684, -0.74368054, -0.28641268],
       [-0.77744209,  0.2952417 ,  1.03224056],
       [-0.79337478, -1.61324985,  0.979882  ]])

In [11]:
# 生成数组
a_zero = np.zeros(12, dtype=int)
print(type(a_zero))
print(a_zero)
print(a_zero.dtype)


<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0]
int32


In [15]:
# 生成数组
a_zero = np.ones((4,5), dtype=int)
print(type(a_zero))
print(a_zero)
print(a_zero.dtype)

<class 'numpy.ndarray'>
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int32


In [17]:
# 生成数组
a_zero = np.full((3,2), 3.12)
print(type(a_zero))
print(a_zero)
print(a_zero.dtype)

<class 'numpy.ndarray'>
[[3.12 3.12]
 [3.12 3.12]
 [3.12 3.12]]
float64


In [23]:
np.zeros_like(a_zero,3.2, dtype=float)

TypeError: _zeros_like_dispatcher() got multiple values for argument 'dtype'

In [32]:
# random
print(np.random.random((5,5)))
# 形成随机数，经常用
print(np.random.randint(0, 10, (5,5)))

[[0.97162423 0.93477091 0.51049365 0.81564045 0.35124704]
 [0.51858926 0.15727973 0.25087125 0.70790401 0.56453562]
 [0.43006479 0.85441291 0.47337883 0.94711502 0.30431062]
 [0.9218403  0.97699851 0.54974331 0.98052963 0.28531869]
 [0.40424161 0.97212202 0.05837961 0.33016909 0.39357828]]
[[1 0 0 1 1]
 [3 0 7 0 1]
 [3 4 2 0 5]
 [4 6 5 7 2]
 [4 0 9 1 3]]


In [33]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [38]:
np.arange(0,10,1)
np.linspace(1,2, 10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [40]:
# 单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# 访问数组中的元素

In [45]:
# 运算
a = np.array(list(range(10)))
print(a + 10)
print(a - 1)
print(a / 2)
print(a * 3)


[10 11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7  8]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  3  6  9 12 15 18 21 24 27]


In [48]:
b = np.array(list(range(10)))
print(np.add(b,a))
print(a - b)
print(a * b)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [60]:
# 统计类型
b = np.array(list(range(13)))

print(b, np.sum(b))
c = np.full((3,3), 3)
print(c,"\n sum=", np.sum(c,axis=1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 78
[[3 3 3]
 [3 3 3]
 [3 3 3]] 
 sum= [9 9 9]


In [65]:
n = np.random.rand(1,10, 10)
print(n)

[[[8.41606720e-01 4.99556617e-01 4.23707210e-01 8.16166389e-01
   9.12023726e-01 8.51921568e-01 8.99523702e-01 8.17519667e-01
   2.84426159e-01 4.18873168e-01]
  [4.00125928e-01 6.39397996e-01 1.55077635e-02 7.23198256e-02
   9.44880742e-01 5.05142127e-01 1.72571133e-01 8.46718862e-01
   7.36137085e-01 7.62778580e-02]
  [1.45628286e-01 4.34439552e-01 3.15940003e-01 6.91213102e-01
   1.37356428e-01 5.67047860e-02 7.01529502e-01 6.47804864e-03
   5.00913003e-01 1.65684321e-01]
  [8.34637399e-02 6.22275253e-02 6.08102164e-01 7.51989366e-01
   5.09370508e-01 7.32388103e-01 5.23836580e-01 9.12180436e-02
   3.50466831e-02 6.37993306e-01]
  [6.89921780e-01 9.93307867e-01 7.67528460e-02 5.15259069e-01
   7.66201268e-01 7.63608728e-01 8.94174052e-01 9.19684273e-01
   2.93317590e-01 2.20806169e-01]
  [4.98750244e-01 6.69717673e-02 3.60002346e-01 7.67127916e-01
   3.98440289e-01 6.75115313e-01 7.84480086e-01 3.51290405e-01
   2.90046053e-01 4.86332004e-01]
  [9.96879428e-01 7.10966737e-01 8.90415

In [73]:
b = np.array(list(range(10040)))
%timeit sum(b)


1.52 ms ± 10.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [71]:
%timeit np.sum(b)

9.04 µs ± 28.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
