In [2]:
import cv2 as cv

import numpy as np
img = cv.imread('QR.png')
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
sift = cv.xfeatures2d.SIFT_create()
kp = sift.detect(gray,None)
img=cv.drawKeypoints(gray,kp,img)

cv.imshow("SIFT", img)
cv.imwrite('sift_keypoints.jpg',img)
cv.waitKey(0)
cv.destroyAllWindows()

error: OpenCV(4.1.1) C:\projects\opencv-python\opencv_contrib\modules\xfeatures2d\src\sift.cpp:1207: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'cv::xfeatures2d::SIFT::create'


In [3]:
import numpy as np

def pyhonsum(n):
    a = list(range(n))
    b = list(range(n))
    c = []

    for i in range(len(a)):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c

def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b 
    return c

print(pyhonsum(10))
print(numpysum(10))

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]
[  0   2  12  36  80 150 252 392 576 810]


In [15]:
# 测试numpy 和 python 代码顺序
import sys
from datetime import datetime
import numpy as np 

'''

'''
n = 100000
def diff_time(n):
    print(n)
    start = datetime.now()
    c = pyhonsum(n)
    end = datetime.now() - start
    print(c[-2:], "python 时间", end.microseconds)

    start = datetime.now()
    c = numpysum(n)
    end = datetime.now() - start
    print(c[-2:], "numpy 时间",end.microseconds)
for i in range(10):
    diff_time(i*1000)

0
[] python 时间 0
[] numpy 时间 0
1000
[995007996, 998001000] python 时间 1029
[995007996 998001000] numpy 时间 0
2000
[7980015996, 7992002000] python 时间 1963
[-609918596 -597932592] numpy 时间 0
3000
[26955023996, 26982003000] python 时间 2989
[1185220220 1212199224] numpy 时间 0
4000
[63920031996, 63968004000] python 时间 3989
[-504477444 -456505440] numpy 时间 0
5000
[124875039996, 124950005000] python 时间 5018
[320988412 395953416] numpy 时间 965
6000
[215820047996, 215928006000] python 时间 5985
[1071683196 1179641200] numpy 时间 0
7000
[342755055996, 342902007000] python 时间 6981
[-842327684 -695376680] numpy 时间 0
8000
[511680063996, 511872008000] python 时间 7978
[578955772 770899776] numpy 时间 0
9000
[728595071996, 728838009000] python 时间 7978
[-1549368324 -1306431320] numpy 时间 0


In [ ]:
# numpy 基础
# 数据类型、数组类型、类型转换、创建数组、数组索引、数组切片、改变维度


In [30]:
# ndarray 1. 数据 2. 描述数据的元数据
# 一维数组
a = np.arange(5)
a.dtype
a.shape
# 多维数组 array函数可以依据给定的对象生成数组
m = np.array([np.arange(5),np.arange(5),np.arange(5)])
print(m)
# 问题1 ndarray对象的维度属性是以下列哪种方式存储的？
# tuple 

# 从数组中选取元素: 对于数组a，只需要用a[m,n]选取各数组元素
m[2,4]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


4

In [6]:
# 兼容Numeric，dtype可以使用字符编码，但是不建议
a = np.arange(5, dtype=np.complex)
a.dtype
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [20]:
# 自定义数据类型是一种异构数据类型，可以当做用来记录电子表格或数据库中一行数据的结构。
a = np.dtype([('name', np.str_, 40),('numitems',np.int32)])
a.char

'V'